name: CI/CD Flow

run-name: Deploy ${{ github.event_name }} by ${{ github.actor }}

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - develop
      - release
      - feature/*
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  standard_flow:
    name: Standard Flow
    uses: ./.github/workflows/build.yaml
    secrets:
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}